# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  use-node-agent:
    description: |
        Controls whether to deploy Velero's optional node agent (file system backup daemonset) on each Kubernetes node
    default: false
    type: boolean
  velero-image:
    description: |
      The Velero container image to deploy
    default: "velero/velero:v1.15.2"
    type: string
  velero-aws-plugin-image:
    description: |
      The Velero AWS plugin container image to deploy
    default: "velero/velero-plugin-for-aws:v1.10.0"
    type: string
  velero-azure-plugin-image:
    description: |
      The Velero Azure plugin container image to deploy
    default: "velero/velero-plugin-for-microsoft-azure:v1.11.0"
    type: string
  velero-gcp-plugin-image:
    description: |
      The Velero GCP plugin container image to deploy
    default: "velero/velero-plugin-for-gcp:v1.14.0"
    type: string
  default-volumes-to-fs-backup:
    description: |
      Controls whether to backup all volumes using the file system backup method
      (requires the node agent to be deployed)
    default: false
    type: boolean
