name: On Pull Request

# On pull_request, we:
# * always run tests
# * always publish to charmhub at latest/edge/branchname

on:
  pull_request:

jobs:

  tests:
    name: Run Tests
    uses: ./.github/workflows/check.yaml
    secrets: inherit

  # publish runs in parallel with tests, as we always publish in this situation
  publish-charm:
    name: Publish Charm
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
